### ISSUE TITLE
프로젝트 초기 환경 설정

### ISSUE THREAD

**Issue by cho7778** [whatever-mentoring/spa-project#1]
## Description
- 프로젝트 초기 환경 설정

## Todo

- [x] 이슈/PR 템플릿 설정
- [x] yarn init
- [x] eslint, prettier 설정
- [x] webpack 서버 구축
